language: c
compiler: clang

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install automake1.10 fftw3 fftw3-dev
  - ./ci/install-gromacs.sh

install:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - sudo make install
  - cd ..

script: ./run_tests
